all:	pdf

pdf: 
	pdflatex presentation.tex
	evince presentation.pdf &
					
clean:
	rm -f presentation.aux presentation.log presentation.blg presentation.bbl presentation.out presentation.dvi presentation.snm presentation.toc presentation.nav

