all:	pdf

pdf: 
	pdflatex presentation.tex
	pdflatex presentation.tex
bib:	
	pdflatex presentation.tex
	bibtex presentation
	pdflatex presentation.tex
					
clean:
	rm -f presentation.aux presentation.log presentation.blg presentation.bbl presentation.out presentation.dvi presentation.snm presentation.toc presentation.nav

